# Generated by Django 5.0 on 2024-05-01 05:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(default='0900000000', max_length=14)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='upload/profile')),
                ('joinedAt', models.DateField(default=datetime.date(2024, 5, 1))),
                ('paidAt', models.DateTimeField(default=datetime.datetime(2024, 5, 1, 8, 55, 1, 229994))),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2024, 5, 1, 8, 55, 1, 229994))),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workoutTime', models.TimeField(default=datetime.datetime(2024, 5, 1, 8, 55, 1, 229994))),
                ('workoutDate', models.DateField(default=datetime.date(2024, 5, 1))),
                ('noPerDay', models.IntegerField(default=0)),
                ('gymMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymManagement.gymmember')),
            ],
        ),
        migrations.AddField(
            model_name='gymmember',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymManagement.plan'),
        ),
    ]
