# Generated by Django 5.0 on 2024-05-01 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0002_alter_attendance_workouttime_alter_gymmember_paidat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='workoutTime',
            field=models.TimeField(default=datetime.datetime(2024, 5, 1, 11, 40, 28, 36661)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='paidAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 11, 40, 28, 36661)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 11, 40, 28, 36661)),
        ),
    ]
