# Generated by Django 5.0 on 2024-05-01 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0003_alter_attendance_workouttime_alter_gymmember_paidat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymmember',
            name='gender',
            field=models.CharField(default='Male', max_length=8),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='workoutTime',
            field=models.TimeField(default=datetime.datetime(2024, 5, 1, 12, 14, 58, 589126)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='paidAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 12, 14, 58, 589127)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='photo',
            field=models.ImageField(blank=True, default='static/assets/img/logo.jpg', null=True, upload_to='upload/profile'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 12, 14, 58, 589127)),
        ),
    ]
