# Generated by Django 5.0 on 2024-05-01 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0004_gymmember_gender_alter_attendance_workouttime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='period',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='workoutTime',
            field=models.TimeField(default=datetime.datetime(2024, 5, 1, 13, 3, 27, 115955)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='paidAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 13, 3, 27, 115956)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 13, 3, 27, 115956)),
        ),
    ]
