# Generated by Django 5.0 on 2024-05-01 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0006_plan_name_alter_attendance_workouttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='workoutTime',
            field=models.TimeField(default=datetime.datetime(2024, 5, 1, 14, 15, 2, 708086)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='paidAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 14, 15, 2, 695558)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='upload/profile'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 14, 15, 2, 695558)),
        ),
    ]
