# Generated by Django 5.0 on 2024-04-30 12:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0007_alter_gymmember_paidat_alter_gymmember_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmember',
            name='paidAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 15, 6, 25, 534618)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymManagement.plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 15, 6, 25, 534618)),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workoutDateTime', models.DateField(default=datetime.datetime(2024, 4, 30, 15, 6, 25, 534618))),
                ('noPerDay', models.IntegerField(default=1)),
                ('gymMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymManagement.gymmember')),
            ],
        ),
    ]
