# Generated by Django 5.0 on 2024-05-05 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0008_alter_attendance_workoutdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymmember',
            name='expireDate',
            field=models.DateField(default=datetime.date(2024, 5, 5)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='workoutDate',
            field=models.DateField(default=datetime.date(2024, 5, 5)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='workoutTime',
            field=models.TimeField(default=datetime.datetime(2024, 5, 5, 5, 37, 1, 629998)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='joinedAt',
            field=models.DateField(default=datetime.date(2024, 5, 5)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='paidAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 5, 37, 1, 629998)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 5, 37, 1, 629998)),
        ),
    ]
