# Generated by Django 5.0 on 2024-04-30 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0008_alter_gymmember_paidat_alter_gymmember_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='noPerDay',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='workoutDateTime',
            field=models.DateField(default=datetime.datetime(2024, 4, 30, 15, 16, 5, 989748)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='paidAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 15, 16, 5, 989748)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 15, 16, 5, 989748)),
        ),
    ]
