# Generated by Django 5.0 on 2024-04-30 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0009_alter_attendance_noperday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='workoutDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 21, 56, 48, 555237)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='paidAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 21, 56, 48, 554692)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 21, 56, 48, 554143)),
        ),
    ]
