# Generated by Django 5.0 on 2024-05-26 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0009_gymmember_expiredate_alter_attendance_workoutdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='workoutDate',
            field=models.DateField(default=datetime.date(2024, 5, 26)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='workoutTime',
            field=models.TimeField(default=datetime.datetime(2024, 5, 26, 11, 40, 8, 252740)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='expireDate',
            field=models.DateField(default=datetime.date(2024, 5, 26)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='joinedAt',
            field=models.DateField(default=datetime.date(2024, 5, 26)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='paidAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 11, 40, 8, 252741)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='photo',
            field=models.ImageField(blank=True, default='upload/profile/defaultUserimg.jpeg', null=True, upload_to='upload/profile'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 11, 40, 8, 251729)),
        ),
    ]
