# Generated by Django 5.0 on 2024-04-30 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0010_alter_attendance_workoutdatetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='workoutDateTime',
        ),
        migrations.AddField(
            model_name='attendance',
            name='workoutTime',
            field=models.DateField(default=datetime.date(2024, 4, 30)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='paidAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 22, 58, 49, 921177)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 22, 58, 49, 921177)),
        ),
    ]
