# Generated by Django 5.0 on 2024-05-28 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0010_alter_attendance_workoutdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='workoutDate',
            field=models.DateField(default=datetime.date(2024, 5, 28)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='workoutTime',
            field=models.TimeField(default=datetime.datetime(2024, 5, 28, 8, 6, 13, 268909)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='expireDate',
            field=models.DateField(default=datetime.date(2024, 5, 28)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='joinedAt',
            field=models.DateField(default=datetime.date(2024, 5, 28)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='paidAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 8, 6, 13, 268910)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 8, 6, 13, 268910)),
        ),
    ]
