# Generated by Django 5.0 on 2024-04-30 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0011_remove_attendance_workoutdatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='workoutDate',
            field=models.DateField(default=datetime.date(2024, 4, 30)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='workoutTime',
            field=models.TimeField(default=datetime.datetime(2024, 4, 30, 23, 1, 19, 810883)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='paidAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 23, 1, 19, 810884)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 23, 1, 19, 810884)),
        ),
    ]
