# Generated by Django 5.0 on 2024-05-29 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0011_alter_attendance_workoutdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='workoutDate',
            field=models.DateField(default=datetime.date(2024, 5, 30)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='workoutTime',
            field=models.TimeField(default=datetime.datetime(2024, 5, 30, 2, 17, 31, 739807)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='expireDate',
            field=models.DateField(default=datetime.date(2024, 5, 30)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='joinedAt',
            field=models.DateField(default=datetime.date(2024, 5, 30)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='paidAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 2, 17, 31, 739807)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='photo',
            field=models.ImageField(blank=True, default='upload/profile/defaultUserImg.jpeg', null=True, upload_to='upload/profile'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 2, 17, 31, 738703)),
        ),
    ]
